version: '3.8'
services:
  db:
    env_file:
      - .env
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  backend:
    env_file:
      - .env
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
