spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB

jwt:
  secret: ${JWT_SECRET}
server:
  error:
    include-message: always
    include-stacktrace: never

file:
  upload:
    cloud-name: ${CLOUD_NAME}
    api-key: ${API_KEY}
    api-secret: ${API_SECRET}